### ISSUE TITLE
Use card in conditional card

### ISSUE THREAD

**Issue by GunnarBjoru** [DurgNomis-drol/google_home_timers_card#24]
First of all, thank you for making this nice card.

I was trying to use the card in a conditional card but found that OR statement is not possible in conditions.
I find this difficult to do since I have to choose either alarm or timer as condition.

I have a google home units and would only show the card if it has a timer OR an alarm.
I have tried to make two separate conditional cards which works fine until I have both an alarm and a timer running. Then I get two equal cards which is not that nice.

If I could get an option to not show both alarms and timers I think it would be better.

**Comment by ejpenney** [comment]
Just my two cents, but I think this bug would be better suited to the Conditional Lovelace card as its the one with the limitation, it probably should have an "operator: and/or" option or something.  In the meantime you can get this to work by creating a binary_sensor that toggles based on both states, with the template platform in configuration.yaml like so:

```binary_sensor:
  - platform: template
    sensors:
      kitchen_timers:
        friendly_name: "Kitchen Alarms/Timers"
        value_template: '{{ states("sensor.kitchen_speaker_timers") != "unavailable" or states("sensor.kitchen_speaker_alarms") != "unavailable" }}'
```

Then set your card to use the binary_sensor like so:

```
type: conditional
conditions:
  - entity: binary_sensor.kitchen_timers
    state: 'on'
card:
  type: custom:googletimers-card
  entity: sensor.kitchen_speaker_timers
  alarms_entity: sensor.kitchen_speaker_alarms
  title: Kitchen

```
