### ISSUE TITLE
More functions?

### ISSUE THREAD

**Issue by stefdewilde** [DurgNomis-drol/google_home_timers_card#5]
Hey man!

This card really works great and I'm really happy to use it!

Is it possible to add an option to have no title on the card? 

Thanks in advance :)

**Comment by DurgNomis-drol** [comment]
@stefdewilde Thanks! Appreciate the feedback. 😄 

I have added a `hide_header` option now.

Example:
```yaml
type: 'custom:googletimers-card'
entity: sensor.kithcen_timers
hide_header: true
```

If you only want to remove the title, you can always set it to `title: " "` (The space is important). This also works on many other cards in Home Assistant.
